name: Docker Deploy Workflow

on:
  push:
    branches:
      - DO/DEV

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.actor }}/actions-go:latest .

    - name: Push Docker image to GitHub Container Registry
      env:
        CR_PAT: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/${{ github.actor }}/actions-go:latest
        