name: Docker Deploy Workflow

on:
  push:
    branches:
      - DO/DEV

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.actor }}/actions-go:latest .

    - name: Push Docker image to GitHub Container Registry
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
      run: |
        echo $CR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/${{ github.actor }}/actions-go:latest
    - name: Trigger DigitalOcean Deployment
      env:
        DO_API_TOKEN: ${{ secrets.DO_API_TOKEN }}
      run: |
        curl -X POST \
          -H "Authorization: Bearer $DO_API_TOKEN" \
          -H "Content-Type: application/json" \
          "https://api.digitalocean.com/v2/apps/rk3436@bard.edu/deployments"
